include:
  - compose.proxy.yaml
  - compose.ha.yaml

services:
  dozzle:
    container_name: dozzle
    image: ghcr.io/amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

networks:
  net:
    external: true
