services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./data/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - $XDG_RUNTIME_DIR/dbus:/run/dbus:ro
    restart: always
    network_mode: host

  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: always
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./data/matter-server:/data
      - $XDG_RUNTIME_DIR/dbus:/run/dbus:ro
    network_mode: host
